server:
  port: ${APP_PORT:8080}
  error:
    # Não inclui o nome da classe da exceção na resposta de erro.
    include-exception: false
    # Nunca inclui o stack trace na resposta. Essencial para segurança em produção.
    include-stacktrace: never
    # Nunca inclui a mensagem da exceção na resposta padrão do Spring.
    # Permite que o GlobalExceptionHandler tenha controle total sobre a mensagem de erro.
    include-message: never

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: always

# Configuração de clientes para serviços externos
clients:
  email-service:
    url: ${EMAIL_SERVICE_URL:http://localhost:8081}

# Configurações de negócio da aplicação
app:
  business:
    event:
      min-duration-minutes: ${EVENT_MIN_DURATION_MINUTES:15}

spring:
  application:
    name: event-microservice
  mvc:
    throw-exception-if-no-handler-found: true
  web:
    resources:
      add-mappings: false
  data:
    web:
      pageable:
        default-page-size: 10
        max-page-size: 100
  datasource:
    url: jdbc:postgresql://localhost:${DB_PORT:5432}/events-db
    username: ${DB_USER:postgres}
    password: ${DB_PASSWORD:postgres}
  jpa:
    show-sql: false
    open-in-view: false
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  flyway:
    # O Flyway usará automaticamente o datasource principal acima.
    locations: classpath:db/migration
    enabled: true
    baseline-on-migrate: true

logging:
  level:
    root: INFO
    com.Samuel.event_microservice: DEBUG
    org.springframework.web: INFO
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql: TRACE
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss.SSS} [%15.15t] %-5level %-40.40logger{39} : %m%n"
  file:
    # Caminho e nome do arquivo de log. Será criado na pasta 'logs' na raiz do projeto.
    name: ./logs/email-service.log
  logback:
    rollingpolicy:
      # Tamanho máximo de cada arquivo de log antes de ser rotacionado.
      max-file-size: 10MB
      # Número máximo de arquivos de log antigos a serem mantidos.
      max-history: 3
      # Nome do padrão para os arquivos de log arquivados.
      file-name-pattern: ./logs/email-service-%d{yyyy-MM-dd}.%i.log
